---
title: "Homework_5"
author: "Meg Hemmerlein"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE)
```

## Choice 2: Recreate Graph

### Load the libraries

```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(lubridate)
library(stringr)
library(ggplot2)
```

### Clean the data

```{r}
# Read the data
homicides <- read.csv("Raw_Data/homicide-data.csv")

# Process the data
baltimore <- homicides %>%
  mutate(city = str_trim(city, side = "right"),
         city_name = paste0(city, ", ", state)) %>%
  filter(city_name == "Baltimore, MD") %>%
  mutate(reported_date = ymd(reported_date),
         month = month(reported_date),
         year = year(reported_date),
         season = case_when(
           month %in% c(11, 12, 1, 2, 3, 4) ~ "Winter",
           month %in% c(5, 6, 7, 8, 9, 10) ~ "Summer")) %>%
  group_by(month, year, season) %>%
  summarize(homicides = n(), .groups = 'drop') %>%
  arrange(year, month) %>%
  mutate(month_year = paste(year, str_pad(month, width = 2, pad = "0"), "01", sep = "-") %>% 
           as.Date())

# Arrest of Freddie Gray
freddie_gray <- as.Date("2015-04-12")
freddie_gray_label <- as.Date("2015-03-01")
arrest_label <- "Arrest of\nFreddie Gray"
```

### Plot the data

```{r fig.width=8, fig.height=2.5}
# Plot
ggplot(baltimore, aes(x = month_year, y = homicides, fill = season)) + 
  geom_col() +
  scale_fill_manual(values = c("Winter" = "lightblue", "Summer" = "lightgray")) +
  scale_x_date(date_breaks = "12 months",
               date_labels = "%Y") +
  theme_dark() +
  labs(x = "Date",
       y = "Monthly Homicides",
       title = "Homicides in Baltimore, MD") +
  geom_smooth(method = NULL, aes(group = 1), color = "blue", size = 1, se = FALSE, span = 0.1, show.legend = F) +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  annotate("text", 
           x = freddie_gray_label, 
           y = 40, 
           label = arrest_label,
           color = "white",
           size = 3, 
           hjust = 1,
           vjust = 0.5) +
  geom_vline(xintercept = freddie_gray, color = "red", linetype = "dashed", size = 1) +
  theme(
    axis.title.x = element_text(size = 9),
    axis.title.y = element_text(size = 9))
```
